user:
  max_name: 50
  max_email: 255
  min_password: 6
  record_page: 10
  gravatar_user: 50
  record_page: 20
  time_token: 2
users_helper:
  size: 80
micropost:
  max_content: 140
  size_gravatar: 50
  size_picture: 5
  width_picture: 300
  height_picture: 300
  max_text_area: 20
follow:
  gravatar_size: 30
